language: node_js
node_js: 8
dist: xenial # Note: dist>=xenial required by microk8s
cache: false # as of 20190709 trav-ci.org started loading garbage from the build cache

services:
  - docker

os:
  - linux
#  - osx

#install: ./tools/travis/test/install.sh
#script: ./tools/travis/test/script.sh

#after_success: ./tools/travis/publishers/cos.sh

jobs:
  include:
#    - stage: npm release
#      env: ""
#      node_js: "8"
#      script:
#        - echo "NPM Deploying Started ..."
#        - echo "Repo name:$TRAVIS_REPO_SLUG"
#        - echo "Branch name:$TRAVIS_BRANCH"
#        - echo "TRAVIS EVENT TYPE:$TRAVIS_EVENT_TYPE"
#      before_deploy:
#        - echo "//registry.npmjs.org/:_authToken=${NPMJS_API_KEY}" > ~/.npmrc
#      deploy:
#        - provider: script
#          script: npm install && npx lerna publish preminor --no-git-tag-version --no-push --canary --yes --dist-tag dev --preid dev.$TRAVIS_BUILD_NUMBER
#          skip_cleanup: true
#          keep_history: true
#          on:
#            branch: master
#            repo: IBM/kui
#            condition: $TRAVIS_EVENT_TYPE = push
#        - provider: script
#          script: npm install && npx lerna publish preminor --no-git-tag-version --no-push --canary --yes --dist-tag nightly --preid nightly.$TRAVIS_BUILD_NUMBER
#          skip_cleanup: true
#          keep_history: true
#          on:
#            branch: master
#            repo: IBM/kui
#            condition: $TRAVIS_EVENT_TYPE = cron
    - stage: official release
      env: ""
      node_js: "8"
      script:
        - echo "starting the release"
      before_script:
        - echo "//registry.npmjs.org/:_authToken=${NPMJS_API_KEY}" > ~/.npmrc
        - npm install
        - cd clients/default
        - npm run build:headless && npm run build:electron
        - cd ../..
      after_script:
      #        - cd packages/kui-builder/dist/publishers/s3
      #        - npm install
      #        - BRANCH="stable.$TRAVIS_BUILD_NUMBER" ./publish.sh
      #        - BRANCH="latest" ./publish.sh
      deploy:
#        - provider: script
#          script: npx lerna publish from-package --yes --dist-tag dev --preid dev.$TRAVIS_BUILD_NUMBER
#          skip_cleanup: true
#          keep_history: true
#          on:
#            branch: testing-for-release
#            repo: composer/kui
#            condition: $TRAVIS_EVENT_TYPE = push && $TRAVIS_COMMIT_MESSAGE =~ ([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: clients/dist/**/*
          skip_cleanup: true
          on:
            branch: automatic-release
            repo: ydarias/kui
            condition: $TRAVIS_EVENT_TYPE = push && $TRAVIS_COMMIT_MESSAGE =~ ([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$



#notifications:
#  webhooks:
#    - https://openwhisk.ng.bluemix.net/api/v1/web/nickm_production/travis-for-kui/done.json
