# necessary for kubeadm-dind
#dist: xenial

language: node_js
node_js: 8
dist: trusty

os:
  - linux
  - osx

env:
  matrix:
    - SCRIPTS="lint.sh typecov.sh"
      LAYERS="core bash-like core-support field-installed-plugins editor"
      MOCHA_TARGETS="webpack electron"
      KUI_USE_PROXY=false
      NEEDS_IBMCLOUD_CLI=true # see plugins/plugin-bash-like/src/test/bash-like/bash-like.ts

    - LAYERS="openwhisk1 openwhisk3 grid"
      MOCHA_TARGETS="webpack electron"
      KUI_USE_PROXY=false
      NEEDS_OPENWHISK=true

    - LAYERS="openwhisk2 openwhisk4"
      MOCHA_TARGETS="electron"
      NEEDS_OPENWHISK=true
      NEEDS_OPENWHISK_API_GATEWAY=true
      NEEDS_OPENWHISK_NODEJS8=true
      NEEDS_OPENWHISK_JAVA8=true
      NEEDS_SECOND_OPENWHISK_AUTH=true # see plugins/plugin-openwhisk/src/test/openwhisk2/auth.ts

    - LAYERS="composer1 composer2 composer3"
      MOCHA_TARGETS="electron"
      NEEDS_OPENWHISK=true

    - WAIT_LAYERS="k8s"
      LAYERS="k8s1 k8s2"
      MOCHA_TARGETS="electron"
      NEEDS_HEADLESS=true
      NEEDS_KUBERNETES=true

    - LAYERS="HEADLESS"
      NEEDS_HEADLESS=true
      NEEDS_OPENWHISK=true
      NEEDS_KUBERNETES=true

  global:
    - TRAVIS_KUBE_VERSION=1.12 # kubeadm-dind
    - TRAVIS_HELM_VERSION=2.13.0 # kubeadm-dind
    - WEBPACK_CLIENT_URL="https://localhost:9080/"
    - TEST_ORG=testorg
    - TEST_SPACE=testspace
    - LOCAL_OPENWHISK=true # allows e.g. openwhisk/src/test/openwhisk1/headless to avoid trying to host set <not-local>
    - IGNORE_CERTS=true # apache-composer needs this, because it doesn't obey INSECURE_SSL in wskprops
    - PATH=bin:$PATH
    - NO_MAC_DMG_INSTALLER=`[[ "$TRAVIS_OS_NAME" == linux ]] && echo true` # we can't build macOS DMG files in linux travis :(
    - WINDOW_WIDTH=1400                   # ! important ! so that clicks don't fail due to elements being off-viewport
    - WINDOW_HEIGHT=1050                  # ! ibid !
    - LINUX_BUILD="${TRAVIS_BUILD_DIR}/clients/default/dist/electron/Kui-linux-x64/Kui" # test against linux electron build
    - OSX_BUILD="${TRAVIS_BUILD_DIR}/clients/default/dist/electron/Kui-darwin-x64/Kui.app/Contents/MacOS/Kui" # test against darwin electron build
    - TEST_FROM_BUILD=`[ "$TRAVIS_OS_NAME" == linux ] && echo "$LINUX_BUILD" || echo "$OSX_BUILD"`
    - BUILD_ENV=production                # please note: used in dist/electron/build.sh with npm prune --production
    - HOMEBREW_NO_AUTO_UPDATE=1           # disable auto update before running brew install, brew upgrade or brew tap

install: ./tools/travis/test/install.sh
script: ./tools/travis/test/script.sh
after_success: ./tools/travis/publishers/cos.sh

notifications:
  webhooks:
    - https://openwhisk.ng.bluemix.net/api/v1/web/nickm_production/travis-for-kui/done.json
